### ISSUE TITLE
coding rules

### ISSUE THREAD

**Issue by igorlimon** [ionut-cristinel/PentaStagiuVara2018Homework#2]
proprietatile private trebuie sa inceapa cu underscore(_) si cu litera mica. Mai multe detalii poti sa gasesti mai jos :)
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

**Comment by ionut-cristinel** [comment]
Aceste reguli au fost predate de Nadia la inceputul stagiului si probabil am mai uitat din ele, am vazut proprietati cu underscore in diferite tutoriale si chiar ma intrebam de sunt scrise asa :) s-a facut lumina, multumesc.
