### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by igorlimon** [ionut-cristinel/PentaStagiuVara2018Homework#3]
codul nu se compileaza deoarece is este folosit doar la verificare tipului unui obiect. Daca vrei sa verifici daca un obiect este null atunci folosesti operatori == sau !=. ex.: 
 if (Name == null) sau  if (Name != null)

https://github.com/ionut-cristinel/PentaStagiuVara2018Homework/blob/6bb33881dfad00d96d18c3d19893d74818a200de/Module02Week01/Homework01Library/FileServiceFirst.cs#L50

**Comment by ionut-cristinel** [comment]
Nu stiu exact la ce te referi dar chiar si asa codul functioneaza, cel putin la mine in visual studio, altfel nu cred ca as fi pus tema pe git, daca avea erori.
Cat despre folosirea lui **is** ai dreptate, i-am atribuit eu o utilitate in plus fara sa-mi dau seama si poate as fi continuat asa daca nu remarcai acest lucru, multumesc.
