### ISSUE TITLE
nume cat mai sugestive

### ISSUE THREAD

**Issue by igorlimon** [ionut-cristinel/PentaStagiuVara2018Homework#5]
Daca ma uit la numele metodei si ce face metoda vad ca doar imparte un string dupa spatiu si returneaza valorile. Recomand ca numele metodelor sa reflecte pe cat se poate de posibil ce fac.  Cand te vei uita peste codul unde este folosita aceasta metoda te vei astepta ca metoda face niste valiadari si dupa returneaza ceva.
https://github.com/ionut-cristinel/PentaStagiuVara2018Homework/blob/6bb33881dfad00d96d18c3d19893d74818a200de/Module02Week01/Homework01Library/Validate.cs#L12

**Comment by ionut-cristinel** [comment]
Da, ai dreptate, din cauza ca atunci cand am creat metoda aveam de gand sa-i dau sarcina de validare a valorii din parametru dar am uitat sa-i schimb  numele atunci cand nu am mai implementat acea functionalitate pentru ea. O sa tin cont pe viitor, neatentie.
