### ISSUE TITLE
refactorizare Factory.cs

### ISSUE THREAD

**Issue by igorlimon** [ionut-cristinel/PentaStagiuVara2018Homework#6]
Incearca sa adaugi cate o interfata pentru clasele Message, Brain, File. In clientul nu va depinde de implementarilor claselor si doar de o interfata. Aceasta iti va permite in caz sa schimbi implementarea pentur una dintre clasa fara sa afectezi codul din Program.cs
https://github.com/ionut-cristinel/PentaStagiuVara2018Homework/blob/6bb33881dfad00d96d18c3d19893d74818a200de/Module02Week01/Homework01Library/Factory.cs#L10

**Comment by ionut-cristinel** [comment]
Am incercat initial sa folosesc interfete in loc de clase abstracte acolo unde era cazul si sa instantiez clasele prin interfetele lor dar ma lovisem de o eroare pe care nu am reusit sa o rezolv, din cauza asta am renuntat la interfete in favoarea claselor abstracte acolo unde aveam problema respectiva. 
Nu mai stiu exact despre ce era vorba dar cred ca era ceva legat de delegati, daca lucram cu un delegat al unei clase ce implementa o interfata imi zicea ca acea interfata nu are definit delegatul respectiv si nici in interfata nu-l puteam creea.
Parca ceva de genul acesta era, daca imi mai aduc bine aminte, cand mai intalnesc acea problema o sa revin cu detalii mai exacte.
